# Generated by Django 5.0.6 on 2024-06-25 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn10', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'ISBN-10 must be exactly 10 characters long.'), django.core.validators.MaxLengthValidator(10, 'ISBN-10 cannot exceed 10 characters in length.')])),
                ('isbn13', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(13, 'ISBN-13 must be exactly 13 characters long.'), django.core.validators.MaxLengthValidator(17, 'ISBN-13 cannot exceed 17 characters in length.')])),
                ('date_of_publication', models.DateField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('book_cover', models.ImageField(upload_to='profile_pictures/')),
                ('author_bio', models.TextField(blank=True, null=True)),
                ('summary_of_book', models.TextField()),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=255)),
                ('format', models.CharField(choices=[('Paperback', 'Paperback'), ('Hardcover', 'Hardcover'), ('Ebook', 'Ebook'), ('Audiobook', 'Audiobook'), ('Chatbook', 'Chatbook')], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('unit_weight', models.IntegerField(blank=True, null=True)),
                ('title_in_original_language', models.CharField(max_length=50, null=True)),
                ('co_publisher', models.CharField(max_length=100, null=True)),
                ('winner', models.TextField(null=True)),
                ('country_of_publication', models.CharField(help_text='Country of publication', max_length=100, null=True)),
                ('designed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('edited_by', models.CharField(blank=True, max_length=50, null=True)),
                ('translated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='book', to='Ailaysa_app.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ailaysa_app.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ailaysa_app.language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='book', to='Ailaysa_app.publisher')),
            ],
        ),
    ]
