# Generated by Django 5.0.6 on 2024-06-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ailaysa_app', '0002_alter_book_book_cover_alter_book_winner'),
        ('seller_auth', '0003_remove_user_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ailaysa_app.format'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
