# Generated by Django 5.0.6 on 2024-07-01 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ailaysa_app", "0003_format_alter_book_author_alter_book_publisher_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="co_publisher",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="country_of_publication",
            field=models.CharField(
                blank=True,
                help_text="Country of publication",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_in_original_language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
