# Generated by Django 5.0.6 on 2024-06-24 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ailaysa_app', '0003_author_publisher_alter_book_format_and_more'),
        ('seller_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='publisher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ailaysa_app.publisher'),
            preserve_default=False,
        ),
    ]
